export const GET = () => {
  const experienceData = [
    // {
    //   id: '1',
    //   position: 'Senior Software Engineer',
    //   companyName: 'Gemicle',
    //   startDate: '2026-01-06T22:00:00.000Z',
    //   projectName: 'Early-stage startup',
    //   responsibilities: [
    //     'Built frontend architecture from scratch with full ownership of technical decisions',
    //     'Designed scalable state management and data flow architecture',
    //     'Developed real-time AI chat interfaces with streaming responses and conversational UX',
    //     'Collaborated closely with design (Figma + MCP workflow) to improve product UX',
    //     'Conducted code reviews and contributed to development quality',
    //   ],
    //   techStack: 'TypeScript, React, React Router, React Hook Form, TanStack Query, Zustand, Tailwind CSS, Storybook, TanStack React Table, Monaco Editor, React Markdown',
    //   tools: 'GitHub, IntelliJ IDEA, Cursor, Claude, Gemini, GIT, Jira, Figma',
    // },
    {
      id: '2',
      position: 'Family Budget Pro (Founder and Developer)',
      companyName: 'Family Budget Pro',
      startDate: '2025-10-01T22:00:00.000Z',
      projectName: 'My own project from scratch',
      linkToProject: 'https://familybudget.pro',
      responsibilities: [
        'Built and launched a full-stack SaaS product from scratch, owning the entire development lifecycle',
        'Designed and implemented scalable backend architecture (PostgreSQL, Prisma, API layer)',
        'Implemented authentication system (NextAuth.js, Google OAuth, email/password with verification)',
        'Integrated subscription payments (WayForPay) and transactional email system (Resend)',
        'Set up production infrastructure (Vercel, Neon, Cloudflare) with CI/CD and domain configuration',
        'Developed responsive UI with custom components and data visualization (MUI, charts)',
        'Designed product architecture, database models, and core business logic',
        'Achieved 95+ Lighthouse performance score',
      ],
      techStack: 'TypeScript, React, Next.js, NextAuth.js, PostgreSQL (Neon), Prisma, Resend, React Hook Form, MUI, TanStack Query',
      tools: 'Vercel, Cloudflare, GitHub, WebStorm, Figma',
    },
    {
      id: '3',
      position: 'Senior Software Engineer/Full Stack Software Engineer',
      companyName: 'Radency',
      startDate: '2023-01-31T22:00:00.000Z',
      // endDate: '2026-04-10T22:00:00.000Z',
      projectName: 'US marketplace for tokenized assets from scratch',
      responsibilities: [
        'Led frontend architecture and development of a marketplace from scratch',
        'Defined technical solutions, task planning, and development workflows',
        'Built and delivered core product features, improving scalability and maintainability',
        'Conducted code reviews and mentored developers',
        'Contributed to backend services (Node.js, Kotlin, Express)',
      ],
      techStack: 'TypeScript, React, Next.js, React Hook Form, Jest + React Testing Library, Material-UI, GraphQL/Apollo, TanStack Query (FKA React Query), Chart.js, Redash, Kotlin, Express.js',
      tools: 'GitLab, WebStorm, GIT, Jira, Figma',
    },
    {
      id: '4',
      position: 'Senior Software Engineer (Web Solutions)',
      companyName: 'Infopulse',
      date: 'Feb. 2020 - Jan. 2023',
      startDate: '2020-01-31T22:00:00.000Z',
      endDate: '2022-12-31T22:00:00.000Z',
      projectName: 'Project 1',
      responsibilities: [
        'Conducted technical interviews and contributed to team hiring decisions',
        'Delivered scalable web and mobile applications used in production environments',
        'Improved UX/UI through proactive feature and product enhancements',
        'Applied TDD practices to ensure code quality and reliability',
        'Built cross-browser support applications and optimized production builds',
      ],
      techStack: 'JavaScript/TypeScript, React, MobX, NodeJS, Webpack, Jest, Docker, React Native',
      tools: 'Azure DevOps, WebStorm, GIT, Jira, Xcode',
    },
    {
      id: '5',
      position: 'Front-End Lead/Senior Software Engineer',
      companyName: 'Infopulse',
      startDate: '2021-06-30T21:00:00.000Z',
      endDate: '2023-08-31T21:00:00.000Z',
      projectName: 'Incognito name (part-time)',
      responsibilities: [
        'Led frontend team, owning planning, estimation, and delivery',
        'Mentored developers and conducted code reviews',
        'Delivered new features and improved development processes',
      ],
      techStack: 'JavaScript/TypeScript, React, Redux, Redux Form, Jest + React Testing Library, Material-UI, Highcharts',
      tools: 'Azure DevOps, WebStorm, GIT, Jira, Zeplin',
    },
    {
      id: '6',
      position: 'Senior Software Engineer/Front End Tech Lead',
      companyName: 'K2Fly (prev Sateva)',
      startDate: '2020-06-30T21:00:00.000Z',
      endDate: '2021-07-31T21:00:00.000Z',
      projectName: 'Enterprise model management platform',
      responsibilities: [
        'Led frontend architecture and development from scratch for an enterprise-grade platform',
        'Defined technical direction, architecture decisions, and development standards',
        'Mentored developers and conducted code reviews',
        'Implemented complex state management (Redux, Redux-Saga) for scalable data flows',
        'Applied TDD practices to ensure code quality and reliability',
      ],
      techStack: 'TypeScript, React, Redux, Redux-Saga, Webpack, Jest, Material-UI, react-awesome-query-builder',
      tools: 'WebStorm, GIT, Jira, Bitbucket',
    },
    {
      id: '7',
      position: 'Senior Javascript Developer',
      companyName: 'Ciklum',
      startDate: '2018-09-30T21:00:00.000Z',
      endDate: '2020-01-31T22:00:00.000Z',
      projectName: 'Risk management platform',
      responsibilities: [
        'Improved application performance through refactoring and code optimization',
        'Participated in frontend architecture planning and feature development',
        'Implemented cross-browser support and optimized production builds (Webpack)',
        'Applied TDD practices and ensured code quality via testing and code reviews',
        'Maintained CI/CD processes using Azure DevOps',
      ],
      techStack: 'JavaScript, React, Redux, styled-components, NodeJS, Webpack, Jest',
      tools: 'Azure, Azure DevOps, WebStorm, Jira',
    },
    {
      id: '8',
      position: 'Middle Javascript Developer',
      companyName: 'GlobalLogic',
      startDate: '2017-06-30T21:00:00.000Z',
      endDate: '2018-09-30T21:00:00.000Z',
      projectName: 'Avid Technology',
      responsibilities: [
        'Developed and maintained reusable component libraries for third-party developers',
        'Built and supported backend services using Node.js',
        'Contributed to CI/CD processes (GitLab, Docker) and production builds (Webpack)',
        'Mentored junior developers and supported cross-team collaboration',
      ],
      techStack: 'JavaScript, React, Redux, SCSS,  NodeJS, Webpack',
      tools: 'IntelliJ IDEA, Jenkins, GitLab, Jira, Docker, Kubernetes',
    },
    {
      id: '9',
      position: 'Junior/Middle Javascript/C# Developer',
      companyName: 'Terrasoft',
      startDate: '2015-11-30T22:00:00.000Z',
      endDate: '2017-06-30T21:00:00.000Z',
      projectName: 'Enterprise CRM platform (marketing, sales, service)',
      responsibilities: [
        'Contributed to development of a large-scale CRM system',
        'Implemented frontend features using MVVM architecture (ExtJS)',
        'Worked with legacy codebase, performing refactoring and feature enhancements',
        'Developed and maintained backend components using C#/.NET',
        'Wrote unit and acceptance tests to ensure code quality',
        'Supported CI processes and participated in code reviews',
      ],
      techStack: 'JavaScript, ExtJS, RequireJS, BackboneJS, C#, .NET, MSSQL, Oracle, CSS, LESS, JSON, NodeJS',
      tools: 'WebStorm, Microsoft Visual Studio, SVN, JIRA',
    },
    {
      id: '10',
      position: 'Junior Frontend Developer',
      companyName: 'Modern Telecom Engineering',
      startDate: '2014-12-31T22:00:00.000Z',
      endDate: '2015-11-30T22:00:00.000Z',
      projectName: 'Internal web applications for telecom company (CRM/ERP systems)',
      responsibilities: [
        'Developed responsive web interfaces and SPA functionality',
        'Contributed to internal CRM/ERP frontend development',
        'Implemented UI features using JavaScript and jQuery',
      ],
      techStack: 'JavaScript, HTML5, CSS3, jQuery, Bootstrap, PHP',
      tools: 'WebStorm',
    },
  ];

  return new Response(JSON.stringify(experienceData), {
    status: 200,
    headers: { 'Content-Type': 'application/json' },
  });
};
