export const GET = () => {
  const experienceData = [
    {
      id: '1',
      position: 'Family Budget Pro (Founder and Developer)',
      companyName: 'Family Budget Pro',
      startDate: '2025-10-01T22:00:00.000Z',
      projectName: 'My own project from scratch',
      linkToProject: 'https://familybudget.pro',
      responsibilities: 'built the project from scratch and delivered the full development lifecycle, Integrated deployment infrastructure using Vercel and Neon (PostgreSQL), implemented email sending via Resend and domain-based email routing through Vercel + Cloudflare, integrated WayForPay to support recurring subscription payments, implemented NextAuth.js with Google login and email/password authentication with email verification, developed a responsive UI optimized for web and mobile using Material-UI and custom design components, designed and implemented database models, API routes, and application logic',
      technologies: 'TypeScript, React, Next.js, NextAuth.js, PostgreSQL (Neon), Prisma, Resend, WayForPay, Cloudflare, React Hook Form, MUI, MUI X Charts, TanStack Query',
      tools: 'GitHub, WebStorm, GIT, Figma, Vercel',
    },
    {
      id: '2',
      position: 'Senior Software Engineer/Full Stack Software Engineer',
      companyName: 'Radency',
      startDate: '2023-01-31T22:00:00.000Z',
      projectName: 'Project from scratch (USA)',
      responsibilities: 'project from scratch, architecture planning (front end), all technical solutions, creating tasks, development of new features, writing unit tests, code review, mentoring, small BackEnd tasks using Kotlin and Express',
      technologies: 'TypeScript, React, Next.js, React Hook Form, JSX, Jest + React Testing Library, Material-UI, GraphQL/Apollo, TanStack Query (FKA React Query), Chart.js, Redash, Kotlin, Express.js',
      tools: 'GitLab, WebStorm, GIT, Jira, Figma, Miro',
    },
    {
      id: '3',
      position: 'Senior Software Engineer (Web Solutions)',
      companyName: 'Infopulse',
      date: 'Feb. 2020 - Jan. 2023',
      startDate: '2020-01-31T22:00:00.000Z',
      endDate: '2022-12-31T22:00:00.000Z',
      projectName: 'Project 1',
      responsibilities: 'technical interviews, building a scalable web app and mobile app, developing new features, writing unit tests, code review, offering and implementing my own ideas for improving UX/UI, a support web application for different browsers, developing via TDD approach (Jest), building production bundles using Webpack',
      technologies: 'JavaScript/TypeScript, React, MobX, JSX, NodeJS, Webpack, Jest, Docker, React Native',
      tools: 'Azure DevOps, WebStorm, GIT, Jira, Xcode',
    },
    {
      id: '4',
      position: 'Front-End Lead/Senior Software Engineer',
      companyName: 'Infopulse',
      startDate: '2021-06-30T21:00:00.000Z',
      endDate: '2023-08-31T21:00:00.000Z',
      projectName: 'Incognito name (part-time)',
      responsibilities: 'front end team lead, mentoring, front end team planning, development of new features, code review, all Scrum activities, investigation, task assessment',
      technologies: 'JavaScript/TypeScript, React, Redux, Redux Form, JSX, Jest + React Testing Library, Material-UI, Highcharts',
      tools: 'Azure DevOps, WebStorm, GIT, Jira, Zeplin',
    },
    {
      id: '5',
      position: 'Senior Software Engineer/Front End Tech Lead',
      companyName: 'K2Fly (prev Sateva)',
      startDate: '2020-06-30T21:00:00.000Z',
      endDate: '2021-07-31T21:00:00.000Z',
      projectName: 'Model Manager Solution',
      responsibilities: 'project from scratch, architecture planning (frontend), all technical solutions, development of new features, writing unit tests, code review, developing via TDD approach (Jest), mentoring',
      technologies: 'TypeScript, React, Redux, Redux-Saga, JSX, Webpack, Jest, Material-UI, react-awesome-query-builder',
      tools: 'WebStorm, GIT, Jira, Bitbucket, Everhour',
    },
    {
      id: '6',
      position: 'Senior Javascript Developer',
      companyName: 'Ciklum',
      startDate: '2018-09-30T21:00:00.000Z',
      endDate: '2020-01-31T22:00:00.000Z',
      projectName: 'Proactima, Risk management',
      responsibilities: 'improving the performance of the application as a result of refactoring and code analysis, discussing user stories with the client, maintaining CI/CD process on VSTS, offering and implementing my own ideas for improving UX/UI, architecture planning, development of new features, UX/UI, writing unit tests, code review, a support web application for different browsers, developing via TDD approach (Jest), building production bundles using Webpack',
      technologies: 'JavaScript, React, React-Bootstrap, Redux, styled-components, JSX, NodeJS, Webpack, Jest',
      tools: 'Azure, Azure DevOps, WebStorm, Jira',
    },
    {
      id: '7',
      position: 'Middle Javascript Developer',
      companyName: 'GlobalLogic',
      startDate: '2017-06-30T21:00:00.000Z',
      endDate: '2018-09-30T21:00:00.000Z',
      projectName: 'Avid Technology',
      responsibilities: 'Creating and supporting reusable components (ES, React, npm packages) for third-party developers, supporting/mentoring another team (Junior team), Developing backend services using NodeJS, developing new features, bugs fixing, refactoring code, writing unit tests, code review, building production bundles using Webpack, configuring nginx, maintaining CI/CD process on Gitlab, with Docker and Rpms',
      technologies: 'JavaScript, React, Redux, JSX, SCSS, JSON, NodeJS, GIT, Webpack',
      tools: 'IntelliJ IDEA, Jenkins, GitLab, Jira, Docker, Kubernetes',
    },
    {
      id: '8',
      position: 'Junior/Middle Javascript/C# Developer',
      companyName: 'Terrasoft',
      startDate: '2015-11-30T22:00:00.000Z',
      endDate: '2017-06-30T21:00:00.000Z',
      projectName: 'CRM for marketing, sales, and service',
      responsibilities: 'participated in architecture planning of tasks, client support, development of new features, bugs fixing, refactoring code (was a lot of legacy code), writing unit tests and acceptance tests (Javascript and C#), code review, developing Front-End (MVVM, ExtJs, LESS, C#) part of the large-scale CRM system, maintaining CI process on TeamCity',
      technologies: 'JavaScript, ExtJS, RequireJS, BackboneJS, C#, .NET, MSSQL, Oracle, CSS, LESS, JSON, NodeJS',
      tools: 'WebStorm, Microsoft Visual Studio, SVN, JIRA',
    },
    {
      id: '9',
      position: 'Junior Frontend Developer',
      companyName: 'Modern Telecom Engineering',
      startDate: '2014-12-31T22:00:00.000Z',
      endDate: '2015-11-30T22:00:00.000Z',
      projectName: 'Internal websites for LLC “MTE”',
      responsibilities: 'implementing responsive web design and entire front-end functionality, designing and developing SPA',
      technologies: 'Bootstrap 3, HTML5, CSS3, JavaScript, jQuery, PHP',
      tools: 'WebStorm',
    },
  ];

  return new Response(JSON.stringify(experienceData), {
    status: 200,
    headers: { 'Content-Type': 'application/json' },
  });
};
